type Request {
  createdAt: Date!
  description: String!
  expiresAt: Date
  id: Int!
  user: Profile!
}

input AddRequestInput {
  description: String!
  expiresAt: Date
  marker: Int!
  notifiable: Boolean!
}

type Mutation {
  addRequest(input: AddRequestInput!): Marker!
}
