type Marker {
  category: Category!
  description: String
  duration: Int!
  expiresAt: Date
  id: Int!
  isSubscribed: Boolean!
  latitude: Float!
  longitude: Float!
  name: String!
  recurrence: String!
  requests: [Request!]!
}

input AddMarkerInput {
  category: Int!
  description: String
  duration: Int!
  expiresAt: Date
  latitude: Float!
  longitude: Float!
  name: String!
  recurrence: String!
}

type Mutation {
  addMarker(input: AddMarkerInput!): [Marker!]!
}

type Query {
  markers: [Marker!]!
}
