type Event {
  marker: Marker!
}

type Subscription {
  date: Date!
  id: Int!
  marker: Marker!
}

type Profile {
  email: String!
  name: String!
}

type User {
  events: [Event!]!
  id: Int!
  profile: Profile!
  subscriptions: [Subscription!]!
}

type Mutation {
  requestMarkerAdministration(id: Int!): User!
  subscribeMarker(id: Int!): User!
  unsubscribeMarker(id: Int!): User!
}

type Query {
  user: User!
}
