type Subscription {
  date: Date!
  marker: Marker!
}

type Profile {
  email: String!
  name: String!
}

type User {
  id: Int!
  profile: Profile!
  subscriptions: [Subscription!]!
}

input SubscribeMarkerInput {
  marker: Int!
}

input UnsubscribeMarkerInput {
  marker: Int!
}

type Mutation {
  subscribeMarker(input: SubscribeMarkerInput!): User!
  unsubscribeMarker(input: UnsubscribeMarkerInput!): User!
}

type Query {
  user: User!
}
